---
- hosts: control
  connection: local
  tasks:

  - name: remove vm and all resources except public ips
    azure_rm_virtualmachine:
      resource_group: nbtest1
      name: "{{ VMNAME }}"
      state: absent
      remove_on_absent:
        - network_interfaces
        - virtual_storage
